# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2



 
    jobs:
      build:
        docker:
          - image: circleci/node:14.18.1
        steps: 
          - checkout
          - run : npm install
          - run : npm test
